### ISSUE TITLE
Small piece of information missing in the lab

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/introduction-to-css-lab#13]
Hi. This is a minor issue, but I wanted to point it out. This lab mentions that there are two options for styling the HTML: internal CSS (CSS within a `<style>` tag) and external CSS (CSS in an external file that is referenced by the `<link>` tag).

However, it forgets to mention a third option: inline CSS (styling an individual element with the `style` attribute). I think it's worth adding in there, just to cover all the options.

This is just a suggestion, so please feel free to take it or leave it.

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Hi @Sdcrouse,

Thanks for the feedback, we've updated the materials to be a little more clear.

Thanks!

**Comment by Sdcrouse** [comment]
You're welcome! Thanks for doing that.
