### ISSUE TITLE
Multiple in-browser IDE file tabs

### ISSUE THREAD

**Issue by rohanphillips** [learn-co-curriculum/introduction-to-css-lab#14]
It'd be nice if the in-browser IDE would allow multiple tabs to be opened at once so viewing files was just a click away.
As it currently stands, if you're working on code that's down the page away, and you click on another file to view something and then come back, the location where you're at has to be relocated.
A 'nice to have' request :)

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases.

As always, thanks for contributing! 💙
