### ISSUE TITLE
Testing font

### ISSUE THREAD

**Issue by sgharms** [learn-co-curriculum/introduction-to-css-lab#7]
font-family: Helvetica Neue;
This throws an error, validation expects quotes.
The value without quotes should be allowed too.

Either swap for something without space, adjust test, both?

**Comment by DanielSeehausen** [comment]
this is a good issue. it appears the CSS spec recommends to, whenever you have a font containing a space, wrap it in quotes: https://www.w3.org/TR/css-fonts-3/#family-name-value

To avoid mistakes in escaping, it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens:

body { font-family: "New Century Schoolbook", serif }

<BODY STYLE="font-family: '21st Century', fantasy">

I am going to push up a branch + pr (for M and S) with the test amended to accept EITHER with or without quotes. If you have an opinion on this and encouraging behavior with the spec, choose to either accept the PR or close and delete branch @sgharms

**Comment by sgharms** [comment]
@DanielSeehausen I agree, I'm not happy with either of these options. Would it be easier just to choose something like `Helvetica` so we don't have to put this issue in front of them so early?
